# Setup
title:               Learning Diary - Nelson Chan
tagline:             "For when I can't remember everything."
description:         'A place for me to write about things that I learned.'
url:                 https://chakflying.github.io/learning-diary
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nelson Chan
  url:               https://nelc.cc
  email:             me@nelc.cc

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
